name: Automated Pull Requests

on: [push]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "master"                      # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        #pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_reviewer: "vaychik"                         # Comma-separated list (no spaces)
        pr_assignee: "vaychik"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr,devops"                               # Comma-separated list (no spaces)
        #pr_milestone: "Milestone 1"                       # Milestone name
        pr_draft: false                                    # Creates pull request as draft
        pr_allow_empty: true    
        github_token: ${{ secrets.PULL_REQUEST_TOKEN }}
        
name: Terraform Plan

on: [pull_request]
jobs:        
  terraform_plan:
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "0.12.29"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip -j terraform_"$tf_version"_linux_amd64.zip -d /tmp/
        sudo mv /tmp/terraform /usr/local/bin/
        
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      run: terraform init -input=false

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
