name: Terraform Plan

on: [pull_request]
      
#defaults:
  #run:
    #working-directory: ./terraform/common/

jobs:
  terraform_plan:
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    if: github.event == 'pull_request' && github.event_path == 'terraform/**'
    steps:
    - uses: actions/checkout@v2

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "0.12.29"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip -j terraform_"$tf_version"_linux_amd64.zip -d /tmp/
        sudo mv /tmp/terraform /usr/local/bin/
        
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init Common
      if: github.event_path == 'terraform/common/**'
      working-directory: ./terraform/common/
      run: terraform init -input=false

    - name: Terraform init Bootstrap
      if: github.event_path == 'terraform/basic_configuration/**'
      working-directory: ./terraform/common/
      run: terraform init -input=false
      
    - name: Terraform Format Common
      if: github.event_path == 'terraform/common/**'
      working-directory: ./terraform/common/
      run: terraform fmt -check

    - name: Terraform Format Bootstrap
      if: github.event_path == 'terraform/basic_configuration/**'
      working-directory: ./terraform/basic_configuration/
      run: terraform fmt -check

    - name: Terraform Plan Common
      if: github.event_path == 'terraform/common/**'
      working-directory: ./terraform/common/
      run: terraform plan

    - name: Terraform Plan Bootstrap
      if: github.event_path == 'terraform/basic_configuration/**'
      working-directory: ./terraform/basic_configuration/
      run: terraform plan
